name: Check minimal import

on:
  pull_request:
    paths:
      - "splink/**"
      - "pyproject.toml"
      - "uv.lock"

permissions: {}

jobs:
  test:
    name: Check minimal import
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup uv (without cache)
        id: setup_uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: false

      - name: Install Python 3.12
        id: install_python312
        run: uv python install 3.12

      - name: Install dependencies
        id: install_dependencies
        run: uv sync --python 3.12 --only-group core

      - name: Check Splink imports
        id: check_splink_imports
        run: uv run --only-group core python -c "import splink"

      - name: Check dependencies installed
        id: check_dependencies_installed
        run: uv pip list
