name: Demo Example Notebooks

on:
  pull_request:
    paths:
      - "splink/**"
      - "docs/demos/examples/**"
      - "!docs/demos/examples/examples_index.md"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

permissions: {}

jobs:
  test-notebooks:
    name: Test ${{ matrix.test-group }} notebook with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        test-group: ["duckdb", "spark", "sqlite"]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup uv (with cache)
        id: setup_uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
          cache-suffix: "${{ runner.os }}-${{ matrix.python-version }}"

      - name: Install Python ${{ matrix.python-version }}
        id: install_python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        id: install_dependencies
        run: uv sync --python ${{ matrix.python-version }} --group demos

      - name: Reduce notebook size
        id: reduce_notebook_size
        run: uv run python scripts/reduce_notebook_runtime.py

      - name: Run tests
        id: run_tests
        run: |
          scripts/run_notebooks.sh demos/examples/${{ matrix.test-group }}
