name: Run splink_demos example notebooks

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: "moj-analytical-services/splink_demos"
          ref: master
          path: "splink_demos/"

      - name: Install environment and check notebooks
        run: |
            cd splink_demos
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install ..
            grep -v "^splink==" requirements.txt > temp && mv temp requirements.txt
            pip install -r requirements.txt
            python ../scripts/make_test_datasets_smaller.py
            find . -type f -name 'example_*ipynb' -print0 | while IFS= read -r -d $'\0' file; do
              if sed -i -E 's/target_rows\s*=\s*[0-9.eE+-]+/target_rows = 10000/g' "$file"; then
                echo "Modified: $file"
              fi
            done
            find . -type f -name 'example_*ipynb' -exec grep -H 'target_rows' {} \;
            python -m pytest --nbmake --nbmake-kernel=python3 example_*ipynb



